# Generated by Django 4.2.7 on 2024-03-07 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricePdfDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price_pdf_file', models.FileField(upload_to='price-lists/')),
                ('published', models.BooleanField(default=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Price PDF Document',
                'verbose_name_plural': 'Price PDF Documents',
                'ordering': ['-published', '-publication_date'],
            },
        ),
    ]
