# Generated by Django 4.2.7 on 2024-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricepdfdoc',
            options={'ordering': ['-published', 'publication_date'], 'verbose_name': 'Price PDF Document', 'verbose_name_plural': 'Price PDF Documents'},
        ),
    ]
