version: '3.6'

services:

  db:
    image: postgres:latest
#    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    env_file: gburod/.env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: UTC
      PGTZ: UTC

  web:
    # image: sirius712/gburod:latest
    container_name: backend
    build: ./gburod
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ./gburod:/app/gburod
    ports:
      - '8000:8000'
    env_file: gburod/.env
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
#    depends_on:
#      -   web
    restart: always

volumes:
  static_value:
  media_value:
  postgres_data:
