version: '3.6'

services:

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #    ports:
    #      - '5432:5432'
    env_file: gburod/.env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: UTC
      PGTZ: UTC

  web:
    # image: sirius712/gburod:latest
    container_name: backend
    build: ./gburod
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - '8000:8000'
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
#      - ./certs/fullchain.pem:/etc/letsencrypt/live/foodcollect.ddns.net/fullchain.pem
#      - ./certs/privkey.pem:/etc/letsencrypt/live/foodcollect.ddns.net/privkey.pem
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      -   web
    restart: always

volumes:
  static_value:
  media_value:
  postgres_data:
