# Generated by Django 4.2.6 on 2023-11-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
