# Generated by Django 4.2.7 on 2024-02-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_posts', '0006_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
