# Generated by Django 4.2.7 on 2024-02-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_license_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
