name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push Docker images to registry
        run: |
          docker build  -t ${{ secrets.DOCKERHUB_USERNAME }}/gburod:latest -f- ./gburod < Dockerfile &&
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin &&
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/order-service:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/deploy/docker/project_oncochr
            sudo sh docker-run.sh
