# Generated by Django 2.2.16 on 2023-05-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубликовать'),
        ),
    ]
