# Generated by Django 2.2.16 on 2023-03-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdegree',
            options={'verbose_name': 'Ученая степень', 'verbose_name_plural': 'Ученые степени'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to='personnels.AcademicDegree', verbose_name='ученая степень'),
        ),
    ]
