# Generated by Django 4.2.6 on 2023-11-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_office_comment_comment_email_rating_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='department',
        ),
    ]
