# Generated by Django 2.2.16 on 2023-07-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0002_rating_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created_at',
            new_name='created',
        ),
    ]
