# Generated by Django 2.2.16 on 2023-03-28 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0003_auto_20230322_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(help_text='Автор комментария', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='persona',
            field=models.ForeignKey(help_text='Комментарий на сотрудника', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='personnels.Persona', verbose_name='Сотрудник'),
        ),
    ]
