# Generated by Django 4.2.6 on 2023-11-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0003_remove_persona_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personadepartment',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_departments', to='personnels.persona'),
        ),
    ]
