# Generated by Django 4.2.6 on 2023-11-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0004_auto_20231013_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='department',
        ),
        migrations.AddField(
            model_name='persona',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='personas', to='personnels.department', verbose_name='Отделения'),
        ),
    ]
