# Generated by Django 4.2.6 on 2023-11-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0005_remove_persona_department_persona_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='persona', to='personnels.department', verbose_name='Отделения'),
        ),
    ]
