# Generated by Django 4.2.6 on 2023-11-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0006_alter_persona_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='departments',
        ),
        migrations.AddField(
            model_name='persona',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to='personnels.department', verbose_name='Отделение'),
        ),
    ]
