# Generated by Django 4.2.6 on 2023-11-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0007_remove_persona_departments_persona_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='department',
        ),
        migrations.CreateModel(
            name='PersonaDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnels.department')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnels.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='departments',
            field=models.ManyToManyField(related_name='persona', through='personnels.PersonaDepartment', to='personnels.department'),
        ),
    ]
