# Generated by Django 2.2.16 on 2023-03-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0007_rating_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='author',
        ),
    ]
