# Generated by Django 2.2.16 on 2023-03-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0008_remove_rating_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='persona_code',
            field=models.IntegerField(null=True, verbose_name='код сотрудника'),
        ),
    ]
