# Generated by Django 4.2.6 on 2023-11-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0009_alter_department_adding_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Номер кабинет',
                'verbose_name_plural': 'Нумерация кабинетов',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to='personnels.office', verbose_name='Кабинет'),
        ),
    ]
