# Generated by Django 4.2.6 on 2023-11-01 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0011_alter_persona_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personadepartment',
            options={'verbose_name': 'отделение сотрудника', 'verbose_name_plural': 'отделение сотрудников'},
        ),
    ]
